spring:
  rabbitmq:
    host: 192.168.15.7
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          max-interval: 5s
          multiplier: 2

exchange-topic:
  order: order.topic
  route: OrderTopic
queue:
  order: OrderQueue
  email: EmailQueue
deadletter:
  queue:
    order: OrderDQL
    email: EmailDLQ
  exchange: order.deadletter
  route:
    order: OrderDeadLetter
    email: EmailDeadLetter
