server:
  port: 8082

queue:
  primeiraFila: fila.primeiraFila
topic:
  primeiroTopico: topico.primeiroTopico

spring:
  # Embedded ActiveMQ Configuration Example
  activemq:
    user:
    password:
    broker-url: tcp://localhost:61616
